/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../app/app-routing.module';
import * as import2 from '@angular/router/src/router_module';
import * as import3 from '@angular/common/src/location/location';
import * as import4 from '@angular/router/src/url_tree';
import * as import5 from '@angular/router/src/router_outlet_map';
import * as import6 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import7 from '@angular/router/src/router_preloader';
import * as import8 from '@angular/core/src/di/injector';
import * as import9 from './components/schedule.component.ngfactory';
import * as import10 from './components/school_config.component.ngfactory';
import * as import11 from './components/participant_crud.component.ngfactory';
import * as import12 from './components/hour_slot_crud.component.ngfactory';
import * as import13 from './components/activity_crud.component.ngfactory';
import * as import14 from './components/teacher_crud.component.ngfactory';
import * as import15 from './components/room_crud.component.ngfactory';
import * as import16 from './components/curriculum_crud.component.ngfactory';
import * as import17 from './components/schedule_slot_crud.component.ngfactory';
import * as import18 from './components/not_found.component.ngfactory';
import * as import19 from '@angular/common/src/location/platform_location';
import * as import20 from '@angular/common/src/location/location_strategy';
import * as import21 from '@angular/core/src/linker/compiler';
import * as import22 from '../../app/components/schedule.component';
import * as import23 from '../../app/components/school_config.component';
import * as import24 from '../../app/components/participant_crud.component';
import * as import25 from '../../app/components/hour_slot_crud.component';
import * as import26 from '../../app/components/activity_crud.component';
import * as import27 from '../../app/components/teacher_crud.component';
import * as import28 from '../../app/components/room_crud.component';
import * as import29 from '../../app/components/curriculum_crud.component';
import * as import30 from '../../app/components/schedule_slot_crud.component';
import * as import31 from '../../app/components/not_found.component';
import * as import32 from '@angular/core/src/application_ref';
import * as import33 from '@angular/router/src/url_handling_strategy';
import * as import34 from '@angular/router/src/route_reuse_strategy';
import * as import35 from '@angular/router/src/router';
import * as import36 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import37 from '@angular/router/src/router_config_loader';
import * as import38 from '@angular/router/src/router_state';
import * as import39 from '@angular/core/src/application_init';
import * as import40 from '@angular/core/src/application_tokens';
class AppRoutingModuleInjector extends import0.NgModuleInjector<import1.AppRoutingModule> {
  _ROUTER_FORROOT_GUARD_0:any;
  _RouterModule_1:import2.RouterModule;
  _AppRoutingModule_2:import1.AppRoutingModule;
  __ROUTER_CONFIGURATION_3:any;
  __LocationStrategy_4:any;
  __Location_5:import3.Location;
  __UrlSerializer_6:import4.DefaultUrlSerializer;
  __RouterOutletMap_7:import5.RouterOutletMap;
  __NgModuleFactoryLoader_8:import6.SystemJsNgModuleLoader;
  __ROUTES_9:any[];
  __Router_10:any;
  __ActivatedRoute_11:any;
  _NoPreloading_12:import7.NoPreloading;
  _PreloadingStrategy_13:any;
  _RouterPreloader_14:import7.RouterPreloader;
  __PreloadAllModules_15:import7.PreloadAllModules;
  __NgProbeToken_16:any[];
  __RouterInitializer_17:import2.RouterInitializer;
  __APP_INITIALIZER_18:any[];
  __ROUTER_INITIALIZER_19:any;
  __APP_BOOTSTRAP_LISTENER_20:any[];
  constructor(parent:import8.Injector) {
    super(parent,[
      import9.ScheduleComponentNgFactory,
      import10.SchoolConfigComponentNgFactory,
      import11.ParticipantCrudComponentNgFactory,
      import12.HourSlotCrudComponentNgFactory,
      import13.ActivityCrudComponentNgFactory,
      import14.TeacherCrudComponentNgFactory,
      import15.RoomCrudComponentNgFactory,
      import16.CurriculumCrudComponentNgFactory,
      import17.ScheduleSlotCrudComponentNgFactory,
      import18.NotFoundComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _ROUTER_CONFIGURATION_3():any {
    if ((this.__ROUTER_CONFIGURATION_3 == null)) { (this.__ROUTER_CONFIGURATION_3 = {}); }
    return this.__ROUTER_CONFIGURATION_3;
  }
  get _LocationStrategy_4():any {
    if ((this.__LocationStrategy_4 == null)) { (this.__LocationStrategy_4 = import2.provideLocationStrategy(this.parent.get(import19.PlatformLocation),this.parent.get(import20.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_3)); }
    return this.__LocationStrategy_4;
  }
  get _Location_5():import3.Location {
    if ((this.__Location_5 == null)) { (this.__Location_5 = new import3.Location(this._LocationStrategy_4)); }
    return this.__Location_5;
  }
  get _UrlSerializer_6():import4.DefaultUrlSerializer {
    if ((this.__UrlSerializer_6 == null)) { (this.__UrlSerializer_6 = new import4.DefaultUrlSerializer()); }
    return this.__UrlSerializer_6;
  }
  get _RouterOutletMap_7():import5.RouterOutletMap {
    if ((this.__RouterOutletMap_7 == null)) { (this.__RouterOutletMap_7 = new import5.RouterOutletMap()); }
    return this.__RouterOutletMap_7;
  }
  get _NgModuleFactoryLoader_8():import6.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_8 == null)) { (this.__NgModuleFactoryLoader_8 = new import6.SystemJsNgModuleLoader(this.parent.get(import21.Compiler),this.parent.get(import6.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_8;
  }
  get _ROUTES_9():any[] {
      if ((this.__ROUTES_9 == null)) { (this.__ROUTES_9 = [[
        {
          path: '',
          redirectTo: '/school',
          pathMatch: 'full'
        }
        ,
        {
          path: 'schedule',
          component: import22.ScheduleComponent
        }
        ,
        {
          path: 'school',
          component: import23.SchoolConfigComponent,
          children: [
            {
              path: 'participant',
              component: import24.ParticipantCrudComponent
            }
            ,
            {
              path: 'hourSlot',
              component: import25.HourSlotCrudComponent
            }
            ,
            {
              path: 'activity',
              component: import26.ActivityCrudComponent
            }
            ,
            {
              path: 'teacher',
              component: import27.TeacherCrudComponent
            }
            ,
            {
              path: 'room',
              component: import28.RoomCrudComponent
            }
            ,
            {
              path: 'curriculum',
              component: import29.CurriculumCrudComponent
            }
            ,
            {
              path: 'scheduleTemplate',
              component: import30.ScheduleSlotCrudComponent
            }

          ]

        }
        ,
        {
          path: '**',
          component: import31.NotFoundComponent
        }

      ]
    ]); }
    return this.__ROUTES_9;
  }
  get _Router_10():any {
    if ((this.__Router_10 == null)) { (this.__Router_10 = import2.setupRouter(this.parent.get(import32.ApplicationRef),this._UrlSerializer_6,this._RouterOutletMap_7,this._Location_5,this,this._NgModuleFactoryLoader_8,this.parent.get(import21.Compiler),this._ROUTES_9,this._ROUTER_CONFIGURATION_3,this.parent.get(import33.UrlHandlingStrategy,(null as any)),this.parent.get(import34.RouteReuseStrategy,(null as any)))); }
    return this.__Router_10;
  }
  get _ActivatedRoute_11():any {
    if ((this.__ActivatedRoute_11 == null)) { (this.__ActivatedRoute_11 = import2.rootRoute(this._Router_10)); }
    return this.__ActivatedRoute_11;
  }
  get _PreloadAllModules_15():import7.PreloadAllModules {
    if ((this.__PreloadAllModules_15 == null)) { (this.__PreloadAllModules_15 = new import7.PreloadAllModules()); }
    return this.__PreloadAllModules_15;
  }
  get _NgProbeToken_16():any[] {
    if ((this.__NgProbeToken_16 == null)) { (this.__NgProbeToken_16 = [import2.routerNgProbeToken()]); }
    return this.__NgProbeToken_16;
  }
  get _RouterInitializer_17():import2.RouterInitializer {
    if ((this.__RouterInitializer_17 == null)) { (this.__RouterInitializer_17 = new import2.RouterInitializer(this)); }
    return this.__RouterInitializer_17;
  }
  get _APP_INITIALIZER_18():any[] {
    if ((this.__APP_INITIALIZER_18 == null)) { (this.__APP_INITIALIZER_18 = [import2.getAppInitializer(this._RouterInitializer_17)]); }
    return this.__APP_INITIALIZER_18;
  }
  get _ROUTER_INITIALIZER_19():any {
    if ((this.__ROUTER_INITIALIZER_19 == null)) { (this.__ROUTER_INITIALIZER_19 = import2.getBootstrapListener(this._RouterInitializer_17)); }
    return this.__ROUTER_INITIALIZER_19;
  }
  get _APP_BOOTSTRAP_LISTENER_20():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_20 == null)) { (this.__APP_BOOTSTRAP_LISTENER_20 = [this._ROUTER_INITIALIZER_19]); }
    return this.__APP_BOOTSTRAP_LISTENER_20;
  }
  createInternal():import1.AppRoutingModule {
    this._ROUTER_FORROOT_GUARD_0 = import2.provideForRootGuard(this.parent.get(import35.Router,(null as any)));
    this._RouterModule_1 = new import2.RouterModule(this._ROUTER_FORROOT_GUARD_0);
    this._AppRoutingModule_2 = new import1.AppRoutingModule();
    this._NoPreloading_12 = new import7.NoPreloading();
    this._PreloadingStrategy_13 = this._NoPreloading_12;
    this._RouterPreloader_14 = new import7.RouterPreloader(this._Router_10,this._NgModuleFactoryLoader_8,this.parent.get(import21.Compiler),this,this._PreloadingStrategy_13);
    return this._AppRoutingModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_0; }
    if ((token === import2.RouterModule)) { return this._RouterModule_1; }
    if ((token === import1.AppRoutingModule)) { return this._AppRoutingModule_2; }
    if ((token === import2.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_3; }
    if ((token === import20.LocationStrategy)) { return this._LocationStrategy_4; }
    if ((token === import3.Location)) { return this._Location_5; }
    if ((token === import4.UrlSerializer)) { return this._UrlSerializer_6; }
    if ((token === import5.RouterOutletMap)) { return this._RouterOutletMap_7; }
    if ((token === import36.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_8; }
    if ((token === import37.ROUTES)) { return this._ROUTES_9; }
    if ((token === import35.Router)) { return this._Router_10; }
    if ((token === import38.ActivatedRoute)) { return this._ActivatedRoute_11; }
    if ((token === import7.NoPreloading)) { return this._NoPreloading_12; }
    if ((token === import7.PreloadingStrategy)) { return this._PreloadingStrategy_13; }
    if ((token === import7.RouterPreloader)) { return this._RouterPreloader_14; }
    if ((token === import7.PreloadAllModules)) { return this._PreloadAllModules_15; }
    if ((token === import32.NgProbeToken)) { return this._NgProbeToken_16; }
    if ((token === import2.RouterInitializer)) { return this._RouterInitializer_17; }
    if ((token === import39.APP_INITIALIZER)) { return this._APP_INITIALIZER_18; }
    if ((token === import2.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_19; }
    if ((token === import40.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_20; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._RouterPreloader_14.ngOnDestroy();
  }
}
export const AppRoutingModuleNgFactory:import0.NgModuleFactory<import1.AppRoutingModule> = new import0.NgModuleFactory(AppRoutingModuleInjector,import1.AppRoutingModule);