/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../app/app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/router/src/router_state';
import * as import9 from '@angular/router/src/router';
import * as import10 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import11 from '../../app/services/schedule.service';
import * as import12 from '../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import13 from '@angular/core/src/linker/query_list';
import * as import14 from '../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import15 from '@angular/core/src/linker/view_container';
import * as import16 from '../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/common/src/location/location_strategy';
import * as import19 from '@angular/router/src/router_outlet_map';
import * as import20 from '@angular/core/src/linker/component_factory_resolver';
import * as import21 from '@angular/router/src/directives/router_link';
import * as import22 from '@angular/router/src/directives/router_link_active';
import * as import23 from '@angular/router/src/directives/router_outlet';
export class Wrapper_AppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AppComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this._changed = false;
    this.context = new import0.AppComponent(p0,p1,p2,p3);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    if ((eventName == 'window:beforeunload')) {
      const pd_sub_0:any = ((<any>this.context.beforeUnloadHander()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AppComponent>;
  _AppComponent_0_3:Wrapper_AppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent_Host0,renderType_AppComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'sch-app',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AppComponent0(this.viewUtils,this,0,this._el_0);
    this._AppComponent_0_3 = new Wrapper_AppComponent(this.injectorGet(import8.ActivatedRoute,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex),this.injectorGet(import10.DomSanitizer,this.parentIndex),this.injectorGet(import11.ScheduleService,this.parentIndex));
    this.compView_0.create(this._AppComponent_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'beforeunload','window'),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.compView_0.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._AppComponent_0_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
export const AppComponentNgFactory:import7.ComponentFactory<import0.AppComponent> = new import7.ComponentFactory<import0.AppComponent>('sch-app',View_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = ([] as any[]);
var renderType_AppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_AppComponent,{});
export class View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _RouterLinkActive_16_3:import12.Wrapper_RouterLinkActive;
  _query_RouterLink_16_0:import13.QueryList<any>;
  _query_RouterLinkWithHref_16_1:import13.QueryList<any>;
  _text_17:any;
  _el_18:any;
  _RouterLinkWithHref_18_3:import14.Wrapper_RouterLinkWithHref;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _RouterLinkWithHref_29_3:import14.Wrapper_RouterLinkWithHref;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _RouterLinkWithHref_32_3:import14.Wrapper_RouterLinkWithHref;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _RouterLinkWithHref_35_3:import14.Wrapper_RouterLinkWithHref;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _RouterLinkWithHref_38_3:import14.Wrapper_RouterLinkWithHref;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _RouterLinkWithHref_41_3:import14.Wrapper_RouterLinkWithHref;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _el_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  /*private*/ _vc_64:import15.ViewContainer;
  _RouterOutlet_64_5:import16.Wrapper_RouterOutlet;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent0,renderType_AppComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'nav',new import3.InlineArray2(2,'class','navbar navbar-toggleable-md fixed-top navbar-light bg-faded'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'button',new import3.InlineArray16(14,'aria-controls','navbarResponsive','aria-expanded','false','aria-label','Toggle navigation','class','navbar-toggler navbar-toggler-right','data-target','#navbarResponsive','data-toggle','collapse','type','button'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'span',new import3.InlineArray2(2,'class','navbar-toggler-icon'),(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n  ',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_2,'a',new import3.InlineArray4(4,'class','navbar-brand','href','/'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'School Scheduler',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray4(4,'class','collapse navbar-collapse','id','navbarResponsive'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'ul',new import3.InlineArray2(2,'class','navbar-nav mt-1'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_14,'li',new import3.InlineArray4(4,'class','nav-item','routerLinkActive','active'),(null as any));
    this._RouterLinkActive_16_3 = new import12.Wrapper_RouterLinkActive(this.parentView.injectorGet(import9.Router,this.parentIndex),new import17.ElementRef(this._el_16),this.renderer,this.ref);
    this._query_RouterLink_16_0 = new import13.QueryList<any>();
    this._query_RouterLinkWithHref_16_1 = new import13.QueryList<any>();
    this._text_17 = this.renderer.createText(this._el_16,'\n                    ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'a',new import3.InlineArray4(4,'class','nav-link','routerLink','/schedule'),(null as any));
    this._RouterLinkWithHref_18_3 = new import14.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import9.Router,this.parentIndex),this.parentView.injectorGet(import8.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import18.LocationStrategy,this.parentIndex));
    this._text_19 = this.renderer.createText(this._el_18,'Schedule',(null as any));
    this._text_20 = this.renderer.createText(this._el_16,'\n                ',(null as any));
    this._text_21 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_14,'li',new import3.InlineArray2(2,'class','nav-item dropdown'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'\n                    ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_22,'a',new import3.InlineArray16(10,'aria-expanded','false','aria-haspopup','true','class','nav-link dropdown-toggle','data-toggle','dropdown','id','schoolDropdown'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'School configuration',(null as any));
    this._text_26 = this.renderer.createText(this._el_22,'\n                    ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_22,'div',new import3.InlineArray4(4,'aria-labelledby','schoolDropdown','class','dropdown-menu'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n                        ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_27,'a',new import3.InlineArray4(4,'class','dropdown-item','routerLink','/school/activity'),(null as any));
    this._RouterLinkWithHref_29_3 = new import14.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import9.Router,this.parentIndex),this.parentView.injectorGet(import8.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import18.LocationStrategy,this.parentIndex));
    this._text_30 = this.renderer.createText(this._el_29,'Activities',(null as any));
    this._text_31 = this.renderer.createText(this._el_27,'\n                        ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_27,'a',new import3.InlineArray4(4,'class','dropdown-item','routerLink','/school/hourSlot'),(null as any));
    this._RouterLinkWithHref_32_3 = new import14.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import9.Router,this.parentIndex),this.parentView.injectorGet(import8.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import18.LocationStrategy,this.parentIndex));
    this._text_33 = this.renderer.createText(this._el_32,'Hour slots',(null as any));
    this._text_34 = this.renderer.createText(this._el_27,'\n                        ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_27,'a',new import3.InlineArray4(4,'class','dropdown-item','routerLink','/school/teacher'),(null as any));
    this._RouterLinkWithHref_35_3 = new import14.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import9.Router,this.parentIndex),this.parentView.injectorGet(import8.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import18.LocationStrategy,this.parentIndex));
    this._text_36 = this.renderer.createText(this._el_35,'Teachers',(null as any));
    this._text_37 = this.renderer.createText(this._el_27,'\n                        ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_27,'a',new import3.InlineArray4(4,'class','dropdown-item','routerLink','/school/room'),(null as any));
    this._RouterLinkWithHref_38_3 = new import14.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import9.Router,this.parentIndex),this.parentView.injectorGet(import8.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import18.LocationStrategy,this.parentIndex));
    this._text_39 = this.renderer.createText(this._el_38,'Rooms',(null as any));
    this._text_40 = this.renderer.createText(this._el_27,'\n                        ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_27,'a',new import3.InlineArray4(4,'class','dropdown-item','routerLink','/school/participant'),(null as any));
    this._RouterLinkWithHref_41_3 = new import14.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import9.Router,this.parentIndex),this.parentView.injectorGet(import8.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import18.LocationStrategy,this.parentIndex));
    this._text_42 = this.renderer.createText(this._el_41,'Student groups',(null as any));
    this._text_43 = this.renderer.createText(this._el_27,'\n                    ',(null as any));
    this._text_44 = this.renderer.createText(this._el_22,'\n                ',(null as any));
    this._text_45 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._text_46 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_12,'div',new import3.InlineArray2(2,'class','navbar-nav ml-auto'),(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'\n                ',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_47,'label',new import3.InlineArray2(2,'class','btn btn-outline-primary btn-file ml-2 mt-2'),(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'\n                    ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_49,'i',new import3.InlineArray2(2,'class','fa fa-upload'),(null as any));
    this._text_52 = this.renderer.createText(this._el_49,' Upload config ',(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_49,'input',new import3.InlineArray8(6,'hidden','','id','file','type','file'),(null as any));
    this._text_54 = this.renderer.createText(this._el_49,'\n                ',(null as any));
    this._text_55 = this.renderer.createText(this._el_47,'\n                ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_47,'button',new import3.InlineArray2(2,'class','btn btn-outline-primary ml-2 mt-2 mb-2'),(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,this._el_56,'i',new import3.InlineArray2(2,'class','fa fa-download'),(null as any));
    this._text_58 = this.renderer.createText(this._el_56,' Save current config',(null as any));
    this._text_59 = this.renderer.createText(this._el_47,'\n            ',(null as any));
    this._text_60 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._text_61 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_62 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_63 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_64 = import3.createRenderElement(this.renderer,parentRenderNode,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_64 = new import15.ViewContainer(64,(null as any),this,this._el_64);
    this._RouterOutlet_64_5 = new import16.Wrapper_RouterOutlet(this.parentView.injectorGet(import19.RouterOutletMap,this.parentIndex),this._vc_64.vcRef,this.parentView.injectorGet(import20.ComponentFactoryResolver,this.parentIndex),(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_18,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_18));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_29,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_29));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_32,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_32));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_35,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_35));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_38,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_38));
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_41,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_41));
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_53,new import3.InlineArray2(2,'change',(null as any)),this.eventHandler(this.handleEvent_53));
    var disposable_7:Function = import3.subscribeToRenderElement(this,this._el_56,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_56));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._text_63,
      this._el_64
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.RouterLinkWithHref) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._RouterLinkWithHref_18_3.context; }
    if (((token === import22.RouterLinkActive) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._RouterLinkActive_16_3.context; }
    if (((token === import21.RouterLinkWithHref) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._RouterLinkWithHref_29_3.context; }
    if (((token === import21.RouterLinkWithHref) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._RouterLinkWithHref_32_3.context; }
    if (((token === import21.RouterLinkWithHref) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._RouterLinkWithHref_35_3.context; }
    if (((token === import21.RouterLinkWithHref) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._RouterLinkWithHref_38_3.context; }
    if (((token === import21.RouterLinkWithHref) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._RouterLinkWithHref_41_3.context; }
    if (((token === import23.RouterOutlet) && (64 === requestNodeIndex))) { return this._RouterOutlet_64_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_16_0_0:any = 'active';
    this._RouterLinkActive_16_3.check_routerLinkActive(currVal_16_0_0,throwOnChange,false);
    this._RouterLinkActive_16_3.ngDoCheck(this,this._el_16,throwOnChange);
    const currVal_18_0_0:any = '/schedule';
    this._RouterLinkWithHref_18_3.check_routerLink(currVal_18_0_0,throwOnChange,false);
    this._RouterLinkWithHref_18_3.ngDoCheck(this,this._el_18,throwOnChange);
    const currVal_29_0_0:any = '/school/activity';
    this._RouterLinkWithHref_29_3.check_routerLink(currVal_29_0_0,throwOnChange,false);
    this._RouterLinkWithHref_29_3.ngDoCheck(this,this._el_29,throwOnChange);
    const currVal_32_0_0:any = '/school/hourSlot';
    this._RouterLinkWithHref_32_3.check_routerLink(currVal_32_0_0,throwOnChange,false);
    this._RouterLinkWithHref_32_3.ngDoCheck(this,this._el_32,throwOnChange);
    const currVal_35_0_0:any = '/school/teacher';
    this._RouterLinkWithHref_35_3.check_routerLink(currVal_35_0_0,throwOnChange,false);
    this._RouterLinkWithHref_35_3.ngDoCheck(this,this._el_35,throwOnChange);
    const currVal_38_0_0:any = '/school/room';
    this._RouterLinkWithHref_38_3.check_routerLink(currVal_38_0_0,throwOnChange,false);
    this._RouterLinkWithHref_38_3.ngDoCheck(this,this._el_38,throwOnChange);
    const currVal_41_0_0:any = '/school/participant';
    this._RouterLinkWithHref_41_3.check_routerLink(currVal_41_0_0,throwOnChange,false);
    this._RouterLinkWithHref_41_3.ngDoCheck(this,this._el_41,throwOnChange);
    this._RouterOutlet_64_5.ngDoCheck(this,this._el_64,throwOnChange);
    this._vc_64.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_16_0.dirty) {
        this._query_RouterLink_16_0.reset(([] as any[]));
        this._RouterLinkActive_16_3.context.links = this._query_RouterLink_16_0;
        this._query_RouterLink_16_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_16_1.dirty) {
        this._query_RouterLinkWithHref_16_1.reset([this._RouterLinkWithHref_18_3.context]);
        this._RouterLinkActive_16_3.context.linksWithHrefs = this._query_RouterLinkWithHref_16_1;
        this._query_RouterLinkWithHref_16_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_16_3.context.ngAfterContentInit(); }
    }
    this._RouterLinkWithHref_18_3.checkHost(this,this,this._el_18,throwOnChange);
    this._RouterLinkWithHref_29_3.checkHost(this,this,this._el_29,throwOnChange);
    this._RouterLinkWithHref_32_3.checkHost(this,this,this._el_32,throwOnChange);
    this._RouterLinkWithHref_35_3.checkHost(this,this,this._el_35,throwOnChange);
    this._RouterLinkWithHref_38_3.checkHost(this,this,this._el_38,throwOnChange);
    this._RouterLinkWithHref_41_3.checkHost(this,this,this._el_41,throwOnChange);
  }
  destroyInternal():void {
    this._vc_64.destroyNestedViews();
    this._RouterLinkWithHref_18_3.ngOnDestroy();
    this._RouterLinkActive_16_3.ngOnDestroy();
    this._RouterLinkWithHref_29_3.ngOnDestroy();
    this._RouterLinkWithHref_32_3.ngOnDestroy();
    this._RouterLinkWithHref_35_3.ngOnDestroy();
    this._RouterLinkWithHref_38_3.ngOnDestroy();
    this._RouterLinkWithHref_41_3.ngOnDestroy();
    this._RouterOutlet_64_5.ngOnDestroy();
  }
  handleEvent_18(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_18_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_29(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_29_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_32(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_32_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_35(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_35_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_38(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_38_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_41(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_41_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_53(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'change')) {
      const pd_sub_0:any = ((<any>this.context.fileChanged($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_56(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.downloadConfig()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}