/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/components/participant_crud.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../app/services/schedule.service';
import * as import9 from '@angular/core/src/linker/view_container';
import * as import10 from '@angular/core/src/change_detection/change_detection_util';
import * as import11 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import12 from '@angular/core/src/linker/template_ref';
import * as import13 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import14 from '@angular/common/src/directives/ng_for';
import * as import15 from '../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import16 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import17 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/forms/src/directives/default_value_accessor';
import * as import20 from '@angular/forms/src/directives/control_value_accessor';
import * as import21 from '@angular/forms/src/directives/ng_model';
import * as import22 from '@angular/forms/src/directives/ng_control';
import * as import23 from '@angular/forms/src/directives/ng_control_status';
import * as import24 from '../../node_modules/@angular/forms/src/directives/number_value_accessor.ngfactory';
import * as import25 from '@angular/forms/src/directives/number_value_accessor';
import * as import26 from '../../node_modules/@angular/forms/src/directives/select_control_value_accessor.ngfactory';
import * as import27 from '../../node_modules/@angular/forms/src/directives/select_multiple_control_value_accessor.ngfactory';
import * as import28 from '@angular/forms/src/directives/select_control_value_accessor';
import * as import29 from '@angular/forms/src/directives/select_multiple_control_value_accessor';
import * as import30 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import31 from '@angular/common/src/directives/ng_if';
import * as import32 from '../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import33 from '@angular/forms/src/directives/ng_form';
import * as import34 from '@angular/forms/src/directives/control_container';
import * as import35 from '../../../app/pipes/filter.pipe';
import * as import36 from '../../../app/pipes/tostring.pipe';
export class Wrapper_ParticipantCrudComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ParticipantCrudComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.ParticipantCrudComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ParticipantCrudComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_ParticipantCrudComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.ParticipantCrudComponent>;
  _ParticipantCrudComponent_0_3:Wrapper_ParticipantCrudComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ParticipantCrudComponent_Host0,renderType_ParticipantCrudComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'sch-participant-crud',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ParticipantCrudComponent0(this.viewUtils,this,0,this._el_0);
    this._ParticipantCrudComponent_0_3 = new Wrapper_ParticipantCrudComponent(this.injectorGet(import8.ScheduleService,this.parentIndex));
    this.compView_0.create(this._ParticipantCrudComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._ParticipantCrudComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ParticipantCrudComponent) && (0 === requestNodeIndex))) { return this._ParticipantCrudComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ParticipantCrudComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ParticipantCrudComponentNgFactory:import7.ComponentFactory<import0.ParticipantCrudComponent> = new import7.ComponentFactory<import0.ParticipantCrudComponent>('sch-participant-crud',View_ParticipantCrudComponent_Host0,import0.ParticipantCrudComponent);
const styles_ParticipantCrudComponent:any[] = ([] as any[]);
class View_ParticipantCrudComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ParticipantCrudComponent1,renderType_ParticipantCrudComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import10.UNINITIALIZED;
    this._expr_3 = import10.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'col-sm-',this.context.$implicit.per10,' font-weight-bold');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_0,'className',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import3.inlineInterpolate(1,'',this.context.$implicit.title,'');
    if (import3.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_1,currVal_3);
      this._expr_3 = currVal_3;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ParticipantCrudComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  _pipe_tostring_1_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ParticipantCrudComponent3,renderType_ParticipantCrudComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import10.UNINITIALIZED;
    this._expr_3 = import10.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._pipe_tostring_1_0 = import3.pureProxy1((<View_ParticipantCrudComponent0>this.parentView.parentView)._pipe_tostring_1.transform.bind((<View_ParticipantCrudComponent0>this.parentView.parentView)._pipe_tostring_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import10.ValueUnwrapper();
    const currVal_2:any = import3.inlineInterpolate(1,'col-sm-',this.context.$implicit.per10,'');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_0,'className',currVal_2);
      this._expr_2 = currVal_2;
    }
    valUnwrapper.reset();
    const currVal_3:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_tostring_1_0,(<View_ParticipantCrudComponent0>this.parentView.parentView)._pipe_tostring_1.transform)(this.parentView.context.$implicit[this.context.$implicit.name])),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_3,currVal_3))) {
      this.renderer.setText(this._text_1,currVal_3);
      this._expr_3 = currVal_3;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ParticipantCrudComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import9.ViewContainer;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import11.Wrapper_NgFor;
  _text_3:any;
  _el_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ParticipantCrudComponent2,renderType_ParticipantCrudComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','row p-2 border-bottom-1'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import9.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import12.TemplateRef_(this,2,this._anchor_2);
    this._NgFor_2_6 = new import11.Wrapper_NgFor(this._vc_2.vcRef,this._TemplateRef_2_5,this.parentView.parentView.injectorGet(import13.IterableDiffers,this.parentView.parentIndex),this.parentView.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_0,'button',new import3.InlineArray8(6,'class','btn btn-primary btn-sm mr-1','data-target','#editor','data-toggle','modal'),(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_4,'i',new import3.InlineArray2(2,'class','fa fa-edit'),(null as any));
    this._text_6 = this.renderer.createText(this._el_4,' Edit',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_0,'button',new import3.InlineArray2(2,'class','btn btn-danger btn-sm mr-1'),(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_8,'i',new import3.InlineArray2(2,'class','fa fa-trash'),(null as any));
    this._text_10 = this.renderer.createText(this._el_8,' Delete',(null as any));
    this._text_11 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_4,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_4));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_8,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_8));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._el_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._el_9,
      this._text_10,
      this._text_11
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import14.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parentView.context.cols;
    this._NgFor_2_6.check_ngForOf(currVal_2_0_0,throwOnChange,false);
    this._NgFor_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_ParticipantCrudComponent3(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
  handleEvent_4(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.edit(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_8(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.delete(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_ParticipantCrudComponent6 extends import1.AppView<any> {
  _el_0:any;
  _DefaultValueAccessor_0_3:import15.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_0_4:any[];
  _NgModel_0_5:import16.Wrapper_NgModel;
  _NgControl_0_6:any;
  _NgControlStatus_0_7:import17.Wrapper_NgControlStatus;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ParticipantCrudComponent6,renderType_ParticipantCrudComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_6 = import10.UNINITIALIZED;
    this._expr_7 = import10.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'input',new import3.InlineArray4(4,'class','form-control','type','text'),(null as any));
    this._DefaultValueAccessor_0_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_0));
    this._NG_VALUE_ACCESSOR_0_4 = [this._DefaultValueAccessor_0_3.context];
    this._NgModel_0_5 = new import16.Wrapper_NgModel((<View_ParticipantCrudComponent4>this.parentView.parentView)._ControlContainer_4_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_0_4);
    this._NgControl_0_6 = this._NgModel_0_5.context;
    this._NgControlStatus_0_7 = new import17.Wrapper_NgControlStatus(this._NgControl_0_6);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_0));
    this._NgModel_0_5.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.DefaultValueAccessor) && (0 === requestNodeIndex))) { return this._DefaultValueAccessor_0_3.context; }
    if (((token === import20.NG_VALUE_ACCESSOR) && (0 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_0_4; }
    if (((token === import21.NgModel) && (0 === requestNodeIndex))) { return this._NgModel_0_5.context; }
    if (((token === import22.NgControl) && (0 === requestNodeIndex))) { return this._NgControl_0_6; }
    if (((token === import23.NgControlStatus) && (0 === requestNodeIndex))) { return this._NgControlStatus_0_7.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DefaultValueAccessor_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_1_0:any = import3.inlineInterpolate(1,'',this.parentView.context.$implicit.name,'');
    this._NgModel_0_5.check_name(currVal_0_1_0,throwOnChange,false);
    const currVal_0_1_1:any = this.parentView.parentView.parentView.context.selected[this.parentView.context.$implicit.name];
    this._NgModel_0_5.check_model(currVal_0_1_1,throwOnChange,false);
    this._NgModel_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    this._NgControlStatus_0_7.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_6:any = (this.parentView.context.$implicit.autofocus? true: (null as any));
    if (import3.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementAttribute(this._el_0,'autofocus',((currVal_6 == null)? (null as any): currVal_6.toString()));
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = (this.parentView.context.$implicit.required? true: (null as any));
    if (import3.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementAttribute(this._el_0,'required',((currVal_7 == null)? (null as any): currVal_7.toString()));
      this._expr_7 = currVal_7;
    }
    this._NgControlStatus_0_7.checkHost(this,this,this._el_0,throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_0_5.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_0_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.parentView.parentView.context.selected[this.parentView.context.$implicit.name] = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_ParticipantCrudComponent7 extends import1.AppView<any> {
  _el_0:any;
  _DefaultValueAccessor_0_3:import15.Wrapper_DefaultValueAccessor;
  _NumberValueAccessor_0_4:import24.Wrapper_NumberValueAccessor;
  _NG_VALUE_ACCESSOR_0_5:any[];
  _NgModel_0_6:import16.Wrapper_NgModel;
  _NgControl_0_7:any;
  _NgControlStatus_0_8:import17.Wrapper_NgControlStatus;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ParticipantCrudComponent7,renderType_ParticipantCrudComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_7 = import10.UNINITIALIZED;
    this._expr_8 = import10.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'input',new import3.InlineArray4(4,'class','form-control','type','number'),(null as any));
    this._DefaultValueAccessor_0_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_0));
    this._NumberValueAccessor_0_4 = new import24.Wrapper_NumberValueAccessor(this.renderer,new import18.ElementRef(this._el_0));
    this._NG_VALUE_ACCESSOR_0_5 = [
      this._DefaultValueAccessor_0_3.context,
      this._NumberValueAccessor_0_4.context
    ]
    ;
    this._NgModel_0_6 = new import16.Wrapper_NgModel((<View_ParticipantCrudComponent4>this.parentView.parentView)._ControlContainer_4_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_0_5);
    this._NgControl_0_7 = this._NgModel_0_6.context;
    this._NgControlStatus_0_8 = new import17.Wrapper_NgControlStatus(this._NgControl_0_7);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(8,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any),'change',(null as any)),this.eventHandler(this.handleEvent_0));
    this._NgModel_0_6.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.DefaultValueAccessor) && (0 === requestNodeIndex))) { return this._DefaultValueAccessor_0_3.context; }
    if (((token === import25.NumberValueAccessor) && (0 === requestNodeIndex))) { return this._NumberValueAccessor_0_4.context; }
    if (((token === import20.NG_VALUE_ACCESSOR) && (0 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_0_5; }
    if (((token === import21.NgModel) && (0 === requestNodeIndex))) { return this._NgModel_0_6.context; }
    if (((token === import22.NgControl) && (0 === requestNodeIndex))) { return this._NgControl_0_7; }
    if (((token === import23.NgControlStatus) && (0 === requestNodeIndex))) { return this._NgControlStatus_0_8.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DefaultValueAccessor_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._NumberValueAccessor_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_2_0:any = import3.inlineInterpolate(1,'',this.parentView.context.$implicit.name,'');
    this._NgModel_0_6.check_name(currVal_0_2_0,throwOnChange,false);
    const currVal_0_2_1:any = this.parentView.parentView.parentView.context.selected[this.parentView.context.$implicit.name];
    this._NgModel_0_6.check_model(currVal_0_2_1,throwOnChange,false);
    this._NgModel_0_6.ngDoCheck(this,this._el_0,throwOnChange);
    this._NgControlStatus_0_8.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_7:any = (this.parentView.context.$implicit.autofocus? true: (null as any));
    if (import3.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementAttribute(this._el_0,'autofocus',((currVal_7 == null)? (null as any): currVal_7.toString()));
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = (this.parentView.context.$implicit.required? true: (null as any));
    if (import3.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementAttribute(this._el_0,'required',((currVal_8 == null)? (null as any): currVal_8.toString()));
      this._expr_8 = currVal_8;
    }
    this._NgControlStatus_0_8.checkHost(this,this,this._el_0,throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_0_6.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_0_3.handleEvent(eventName,$event) && result);
    result = (this._NumberValueAccessor_0_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.parentView.parentView.context.selected[this.parentView.context.$implicit.name] = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_ParticipantCrudComponent8 extends import1.AppView<any> {
  _el_0:any;
  _DefaultValueAccessor_0_3:import15.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_0_4:any[];
  _NgModel_0_5:import16.Wrapper_NgModel;
  _NgControl_0_6:any;
  _NgControlStatus_0_7:import17.Wrapper_NgControlStatus;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ParticipantCrudComponent8,renderType_ParticipantCrudComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_6 = import10.UNINITIALIZED;
    this._expr_7 = import10.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'input',new import3.InlineArray4(4,'class','form-control','type','time'),(null as any));
    this._DefaultValueAccessor_0_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_0));
    this._NG_VALUE_ACCESSOR_0_4 = [this._DefaultValueAccessor_0_3.context];
    this._NgModel_0_5 = new import16.Wrapper_NgModel((<View_ParticipantCrudComponent4>this.parentView.parentView)._ControlContainer_4_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_0_4);
    this._NgControl_0_6 = this._NgModel_0_5.context;
    this._NgControlStatus_0_7 = new import17.Wrapper_NgControlStatus(this._NgControl_0_6);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_0));
    this._NgModel_0_5.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.DefaultValueAccessor) && (0 === requestNodeIndex))) { return this._DefaultValueAccessor_0_3.context; }
    if (((token === import20.NG_VALUE_ACCESSOR) && (0 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_0_4; }
    if (((token === import21.NgModel) && (0 === requestNodeIndex))) { return this._NgModel_0_5.context; }
    if (((token === import22.NgControl) && (0 === requestNodeIndex))) { return this._NgControl_0_6; }
    if (((token === import23.NgControlStatus) && (0 === requestNodeIndex))) { return this._NgControlStatus_0_7.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DefaultValueAccessor_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_1_0:any = import3.inlineInterpolate(1,'',this.parentView.context.$implicit.name,'');
    this._NgModel_0_5.check_name(currVal_0_1_0,throwOnChange,false);
    const currVal_0_1_1:any = this.parentView.parentView.parentView.context.selected[this.parentView.context.$implicit.name];
    this._NgModel_0_5.check_model(currVal_0_1_1,throwOnChange,false);
    this._NgModel_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    this._NgControlStatus_0_7.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_6:any = (this.parentView.context.$implicit.autofocus? true: (null as any));
    if (import3.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementAttribute(this._el_0,'autofocus',((currVal_6 == null)? (null as any): currVal_6.toString()));
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = (this.parentView.context.$implicit.required? true: (null as any));
    if (import3.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementAttribute(this._el_0,'required',((currVal_7 == null)? (null as any): currVal_7.toString()));
      this._expr_7 = currVal_7;
    }
    this._NgControlStatus_0_7.checkHost(this,this,this._el_0,throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_0_5.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_0_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.parentView.parentView.context.selected[this.parentView.context.$implicit.name] = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_ParticipantCrudComponent10 extends import1.AppView<any> {
  _el_0:any;
  _NgSelectOption_0_3:import26.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_0_4:import27.Wrapper_NgSelectMultipleOption;
  _text_1:any;
  /*private*/ _expr_4:any;
  _pipe_tostring_1_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ParticipantCrudComponent10,renderType_ParticipantCrudComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_4 = import10.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'option',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSelectOption_0_3 = new import26.Wrapper_NgSelectOption(new import18.ElementRef(this._el_0),this.renderer,(null as any));
    this._NgSelectMultipleOption_0_4 = new import27.Wrapper_NgSelectMultipleOption(new import18.ElementRef(this._el_0),this.renderer,(<View_ParticipantCrudComponent9>this.parentView)._SelectMultipleControlValueAccessor_0_3.context);
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._pipe_tostring_1_1 = import3.pureProxy1((<View_ParticipantCrudComponent0>this.parentView.parentView.parentView.parentView)._pipe_tostring_1.transform.bind((<View_ParticipantCrudComponent0>this.parentView.parentView.parentView.parentView)._pipe_tostring_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import28.NgSelectOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectOption_0_3.context; }
    if (((token === import29.NgSelectMultipleOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectMultipleOption_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import10.ValueUnwrapper();
    const currVal_0_0_0:any = this.context.$implicit;
    this._NgSelectOption_0_3.check_ngValue(currVal_0_0_0,throwOnChange,false);
    this._NgSelectOption_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_1_0:any = this.context.$implicit;
    this._NgSelectMultipleOption_0_4.check_ngValue(currVal_0_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    valUnwrapper.reset();
    const currVal_4:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_tostring_1_1,(<View_ParticipantCrudComponent0>this.parentView.parentView.parentView.parentView)._pipe_tostring_1.transform)(this.context.$implicit)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_4,currVal_4))) {
      this.renderer.setText(this._text_1,currVal_4);
      this._expr_4 = currVal_4;
    }
  }
  destroyInternal():void {
    this._NgSelectOption_0_3.ngOnDestroy();
    this._NgSelectMultipleOption_0_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ParticipantCrudComponent9 extends import1.AppView<any> {
  _el_0:any;
  _SelectMultipleControlValueAccessor_0_3:import27.Wrapper_SelectMultipleControlValueAccessor;
  _NG_VALUE_ACCESSOR_0_4:any[];
  _NgModel_0_5:import16.Wrapper_NgModel;
  _NgControl_0_6:any;
  _NgControlStatus_0_7:import17.Wrapper_NgControlStatus;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import9.ViewContainer;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import11.Wrapper_NgFor;
  _text_3:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ParticipantCrudComponent9,renderType_ParticipantCrudComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_12 = import10.UNINITIALIZED;
    this._expr_13 = import10.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'select',new import3.InlineArray4(4,'class','form-control ','multiple',''),(null as any));
    this._SelectMultipleControlValueAccessor_0_3 = new import27.Wrapper_SelectMultipleControlValueAccessor(this.renderer,new import18.ElementRef(this._el_0));
    this._NG_VALUE_ACCESSOR_0_4 = [this._SelectMultipleControlValueAccessor_0_3.context];
    this._NgModel_0_5 = new import16.Wrapper_NgModel((<View_ParticipantCrudComponent4>this.parentView.parentView)._ControlContainer_4_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_0_4);
    this._NgControl_0_6 = this._NgModel_0_5.context;
    this._NgControlStatus_0_7 = new import17.Wrapper_NgControlStatus(this._NgControl_0_6);
    this._text_1 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import9.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import12.TemplateRef_(this,2,this._anchor_2);
    this._NgFor_2_6 = new import11.Wrapper_NgFor(this._vc_2.vcRef,this._TemplateRef_2_5,this.parentView.parentView.parentView.parentView.injectorGet(import13.IterableDiffers,this.parentView.parentView.parentView.parentIndex),this.parentView.parentView.parentView.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n                         ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(6,'ngModelChange',(null as any),'change',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_0));
    this._NgModel_0_5.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import14.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6.context; }
    if (((token === import29.SelectMultipleControlValueAccessor) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._SelectMultipleControlValueAccessor_0_3.context; }
    if (((token === import20.NG_VALUE_ACCESSOR) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._NG_VALUE_ACCESSOR_0_4; }
    if (((token === import21.NgModel) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._NgModel_0_5.context; }
    if (((token === import22.NgControl) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._NgControl_0_6; }
    if (((token === import23.NgControlStatus) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._NgControlStatus_0_7.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SelectMultipleControlValueAccessor_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_1_0:any = import3.inlineInterpolate(1,'',this.parentView.context.$implicit.name,'');
    this._NgModel_0_5.check_name(currVal_0_1_0,throwOnChange,false);
    const currVal_0_1_1:any = this.parentView.parentView.parentView.context.selected[this.parentView.context.$implicit.name];
    this._NgModel_0_5.check_model(currVal_0_1_1,throwOnChange,false);
    this._NgModel_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    this._NgControlStatus_0_7.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_2_0_0:any = this.parentView.context.$implicit.source;
    this._NgFor_2_6.check_ngForOf(currVal_2_0_0,throwOnChange,false);
    this._NgFor_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
    const currVal_12:any = (this.parentView.context.$implicit.autofocus? true: (null as any));
    if (import3.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementAttribute(this._el_0,'autofocus',((currVal_12 == null)? (null as any): currVal_12.toString()));
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = (this.parentView.context.$implicit.required? true: (null as any));
    if (import3.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementAttribute(this._el_0,'required',((currVal_13 == null)? (null as any): currVal_13.toString()));
      this._expr_13 = currVal_13;
    }
    this._NgControlStatus_0_7.checkHost(this,this,this._el_0,throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
    this._NgModel_0_5.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_ParticipantCrudComponent10(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._SelectMultipleControlValueAccessor_0_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.parentView.parentView.context.selected[this.parentView.context.$implicit.name] = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_ParticipantCrudComponent12 extends import1.AppView<any> {
  _el_0:any;
  _NgSelectOption_0_3:import26.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_0_4:import27.Wrapper_NgSelectMultipleOption;
  _text_1:any;
  /*private*/ _expr_4:any;
  _pipe_tostring_1_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ParticipantCrudComponent12,renderType_ParticipantCrudComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_4 = import10.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'option',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSelectOption_0_3 = new import26.Wrapper_NgSelectOption(new import18.ElementRef(this._el_0),this.renderer,(<View_ParticipantCrudComponent11>this.parentView)._SelectControlValueAccessor_0_3.context);
    this._NgSelectMultipleOption_0_4 = new import27.Wrapper_NgSelectMultipleOption(new import18.ElementRef(this._el_0),this.renderer,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._pipe_tostring_1_2 = import3.pureProxy1((<View_ParticipantCrudComponent0>this.parentView.parentView.parentView.parentView)._pipe_tostring_1.transform.bind((<View_ParticipantCrudComponent0>this.parentView.parentView.parentView.parentView)._pipe_tostring_1));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import28.NgSelectOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectOption_0_3.context; }
    if (((token === import29.NgSelectMultipleOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectMultipleOption_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import10.ValueUnwrapper();
    const currVal_0_0_0:any = this.context.$implicit;
    this._NgSelectOption_0_3.check_ngValue(currVal_0_0_0,throwOnChange,false);
    this._NgSelectOption_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_1_0:any = this.context.$implicit;
    this._NgSelectMultipleOption_0_4.check_ngValue(currVal_0_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    valUnwrapper.reset();
    const currVal_4:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_tostring_1_2,(<View_ParticipantCrudComponent0>this.parentView.parentView.parentView.parentView)._pipe_tostring_1.transform)(this.context.$implicit)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_4,currVal_4))) {
      this.renderer.setText(this._text_1,currVal_4);
      this._expr_4 = currVal_4;
    }
  }
  destroyInternal():void {
    this._NgSelectOption_0_3.ngOnDestroy();
    this._NgSelectMultipleOption_0_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ParticipantCrudComponent11 extends import1.AppView<any> {
  _el_0:any;
  _SelectControlValueAccessor_0_3:import26.Wrapper_SelectControlValueAccessor;
  _NG_VALUE_ACCESSOR_0_4:any[];
  _NgModel_0_5:import16.Wrapper_NgModel;
  _NgControl_0_6:any;
  _NgControlStatus_0_7:import17.Wrapper_NgControlStatus;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import9.ViewContainer;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import11.Wrapper_NgFor;
  _text_3:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ParticipantCrudComponent11,renderType_ParticipantCrudComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_12 = import10.UNINITIALIZED;
    this._expr_13 = import10.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'select',new import3.InlineArray2(2,'class','form-control '),(null as any));
    this._SelectControlValueAccessor_0_3 = new import26.Wrapper_SelectControlValueAccessor(this.renderer,new import18.ElementRef(this._el_0));
    this._NG_VALUE_ACCESSOR_0_4 = [this._SelectControlValueAccessor_0_3.context];
    this._NgModel_0_5 = new import16.Wrapper_NgModel((<View_ParticipantCrudComponent4>this.parentView.parentView)._ControlContainer_4_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_0_4);
    this._NgControl_0_6 = this._NgModel_0_5.context;
    this._NgControlStatus_0_7 = new import17.Wrapper_NgControlStatus(this._NgControl_0_6);
    this._text_1 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import9.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import12.TemplateRef_(this,2,this._anchor_2);
    this._NgFor_2_6 = new import11.Wrapper_NgFor(this._vc_2.vcRef,this._TemplateRef_2_5,this.parentView.parentView.parentView.parentView.injectorGet(import13.IterableDiffers,this.parentView.parentView.parentView.parentIndex),this.parentView.parentView.parentView.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n                         ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(6,'ngModelChange',(null as any),'change',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_0));
    this._NgModel_0_5.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import14.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6.context; }
    if (((token === import28.SelectControlValueAccessor) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._SelectControlValueAccessor_0_3.context; }
    if (((token === import20.NG_VALUE_ACCESSOR) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._NG_VALUE_ACCESSOR_0_4; }
    if (((token === import21.NgModel) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._NgModel_0_5.context; }
    if (((token === import22.NgControl) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._NgControl_0_6; }
    if (((token === import23.NgControlStatus) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._NgControlStatus_0_7.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SelectControlValueAccessor_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_1_0:any = import3.inlineInterpolate(1,'',this.parentView.context.$implicit.name,'');
    this._NgModel_0_5.check_name(currVal_0_1_0,throwOnChange,false);
    const currVal_0_1_1:any = this.parentView.parentView.parentView.context.selected[this.parentView.context.$implicit.name];
    this._NgModel_0_5.check_model(currVal_0_1_1,throwOnChange,false);
    this._NgModel_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    this._NgControlStatus_0_7.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_2_0_0:any = this.parentView.context.$implicit.source;
    this._NgFor_2_6.check_ngForOf(currVal_2_0_0,throwOnChange,false);
    this._NgFor_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
    const currVal_12:any = (this.parentView.context.$implicit.autofocus? true: (null as any));
    if (import3.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementAttribute(this._el_0,'autofocus',((currVal_12 == null)? (null as any): currVal_12.toString()));
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = (this.parentView.context.$implicit.required? true: (null as any));
    if (import3.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementAttribute(this._el_0,'required',((currVal_13 == null)? (null as any): currVal_13.toString()));
      this._expr_13 = currVal_13;
    }
    this._NgControlStatus_0_7.checkHost(this,this,this._el_0,throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
    this._NgModel_0_5.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_ParticipantCrudComponent12(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._SelectControlValueAccessor_0_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.parentView.parentView.context.selected[this.parentView.context.$implicit.name] = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_ParticipantCrudComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _anchor_5:any;
  /*private*/ _vc_5:import9.ViewContainer;
  _TemplateRef_5_5:any;
  _NgIf_5_6:import30.Wrapper_NgIf;
  _text_6:any;
  _anchor_7:any;
  /*private*/ _vc_7:import9.ViewContainer;
  _TemplateRef_7_5:any;
  _NgIf_7_6:import30.Wrapper_NgIf;
  _text_8:any;
  _anchor_9:any;
  /*private*/ _vc_9:import9.ViewContainer;
  _TemplateRef_9_5:any;
  _NgIf_9_6:import30.Wrapper_NgIf;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _vc_11:import9.ViewContainer;
  _TemplateRef_11_5:any;
  _NgIf_11_6:import30.Wrapper_NgIf;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _vc_13:import9.ViewContainer;
  _TemplateRef_13_5:any;
  _NgIf_13_6:import30.Wrapper_NgIf;
  _text_14:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ParticipantCrudComponent5,renderType_ParticipantCrudComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_30 = import10.UNINITIALIZED;
    this._expr_31 = import10.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._anchor_5 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_5 = new import9.ViewContainer(5,0,this,this._anchor_5);
    this._TemplateRef_5_5 = new import12.TemplateRef_(this,5,this._anchor_5);
    this._NgIf_5_6 = new import30.Wrapper_NgIf(this._vc_5.vcRef,this._TemplateRef_5_5);
    this._text_6 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._anchor_7 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_7 = new import9.ViewContainer(7,0,this,this._anchor_7);
    this._TemplateRef_7_5 = new import12.TemplateRef_(this,7,this._anchor_7);
    this._NgIf_7_6 = new import30.Wrapper_NgIf(this._vc_7.vcRef,this._TemplateRef_7_5);
    this._text_8 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._anchor_9 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_9 = new import9.ViewContainer(9,0,this,this._anchor_9);
    this._TemplateRef_9_5 = new import12.TemplateRef_(this,9,this._anchor_9);
    this._NgIf_9_6 = new import30.Wrapper_NgIf(this._vc_9.vcRef,this._TemplateRef_9_5);
    this._text_10 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_11 = new import9.ViewContainer(11,0,this,this._anchor_11);
    this._TemplateRef_11_5 = new import12.TemplateRef_(this,11,this._anchor_11);
    this._NgIf_11_6 = new import30.Wrapper_NgIf(this._vc_11.vcRef,this._TemplateRef_11_5);
    this._text_12 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_13 = new import9.ViewContainer(13,0,this,this._anchor_13);
    this._TemplateRef_13_5 = new import12.TemplateRef_(this,13,this._anchor_13);
    this._NgIf_13_6 = new import30.Wrapper_NgIf(this._vc_13.vcRef,this._TemplateRef_13_5);
    this._text_14 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._anchor_5,
      this._text_6,
      this._anchor_7,
      this._text_8,
      this._anchor_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._anchor_13,
      this._text_14
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (5 === requestNodeIndex))) { return this._TemplateRef_5_5; }
    if (((token === import31.NgIf) && (5 === requestNodeIndex))) { return this._NgIf_5_6.context; }
    if (((token === import12.TemplateRef) && (7 === requestNodeIndex))) { return this._TemplateRef_7_5; }
    if (((token === import31.NgIf) && (7 === requestNodeIndex))) { return this._NgIf_7_6.context; }
    if (((token === import12.TemplateRef) && (9 === requestNodeIndex))) { return this._TemplateRef_9_5; }
    if (((token === import31.NgIf) && (9 === requestNodeIndex))) { return this._NgIf_9_6.context; }
    if (((token === import12.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import31.NgIf) && (11 === requestNodeIndex))) { return this._NgIf_11_6.context; }
    if (((token === import12.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import31.NgIf) && (13 === requestNodeIndex))) { return this._NgIf_13_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_5_0_0:any = (this.context.$implicit.type === 'text');
    this._NgIf_5_6.check_ngIf(currVal_5_0_0,throwOnChange,false);
    this._NgIf_5_6.ngDoCheck(this,this._anchor_5,throwOnChange);
    const currVal_7_0_0:any = (this.context.$implicit.type === 'number');
    this._NgIf_7_6.check_ngIf(currVal_7_0_0,throwOnChange,false);
    this._NgIf_7_6.ngDoCheck(this,this._anchor_7,throwOnChange);
    const currVal_9_0_0:any = (this.context.$implicit.type === 'time');
    this._NgIf_9_6.check_ngIf(currVal_9_0_0,throwOnChange,false);
    this._NgIf_9_6.ngDoCheck(this,this._anchor_9,throwOnChange);
    const currVal_11_0_0:any = (this.context.$implicit.type === 'multiselect');
    this._NgIf_11_6.check_ngIf(currVal_11_0_0,throwOnChange,false);
    this._NgIf_11_6.ngDoCheck(this,this._anchor_11,throwOnChange);
    const currVal_13_0_0:any = (this.context.$implicit.type === 'select');
    this._NgIf_13_6.check_ngIf(currVal_13_0_0,throwOnChange,false);
    this._NgIf_13_6.ngDoCheck(this,this._anchor_13,throwOnChange);
    this._vc_5.detectChangesInNestedViews(throwOnChange);
    this._vc_7.detectChangesInNestedViews(throwOnChange);
    this._vc_9.detectChangesInNestedViews(throwOnChange);
    this._vc_11.detectChangesInNestedViews(throwOnChange);
    this._vc_13.detectChangesInNestedViews(throwOnChange);
    const currVal_30:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementProperty(this._el_2,'htmlFor',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = import3.inlineInterpolate(1,'',this.context.$implicit.title,'');
    if (import3.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setText(this._text_3,currVal_31);
      this._expr_31 = currVal_31;
    }
  }
  destroyInternal():void {
    this._vc_5.destroyNestedViews();
    this._vc_7.destroyNestedViews();
    this._vc_9.destroyNestedViews();
    this._vc_11.destroyNestedViews();
    this._vc_13.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 5)) { return new View_ParticipantCrudComponent6(this.viewUtils,this,5,this._anchor_5,this._vc_5); }
    if ((nodeIndex == 7)) { return new View_ParticipantCrudComponent7(this.viewUtils,this,7,this._anchor_7,this._vc_7); }
    if ((nodeIndex == 9)) { return new View_ParticipantCrudComponent8(this.viewUtils,this,9,this._anchor_9,this._vc_9); }
    if ((nodeIndex == 11)) { return new View_ParticipantCrudComponent9(this.viewUtils,this,11,this._anchor_11,this._vc_11); }
    if ((nodeIndex == 13)) { return new View_ParticipantCrudComponent11(this.viewUtils,this,13,this._anchor_13,this._vc_13); }
    return (null as any);
  }
}
class View_ParticipantCrudComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _NgForm_4_3:import32.Wrapper_NgForm;
  _ControlContainer_4_4:any;
  _NgControlStatusGroup_4_5:import17.Wrapper_NgControlStatusGroup;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _anchor_20:any;
  /*private*/ _vc_20:import9.ViewContainer;
  _TemplateRef_20_5:any;
  _NgFor_20_6:import11.Wrapper_NgFor;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ParticipantCrudComponent4,renderType_ParticipantCrudComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray8(6,'class','modal fade','data-backdrop','','id','editor'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray4(4,'class','modal-dialog','role','document'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'form',new import3.InlineArray2(2,'class','modal-content'),(null as any));
    this._NgForm_4_3 = new import32.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_4_4 = this._NgForm_4_3.context;
    this._NgControlStatusGroup_4_5 = new import17.Wrapper_NgControlStatusGroup(this._ControlContainer_4_4);
    this._text_5 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','modal-header'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'h5',new import3.InlineArray2(2,'class','modal-title'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'Edit',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n                    ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_6,'button',new import3.InlineArray8(8,'aria-label','Close','class','close','data-dismiss','modal','type','button'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n                                ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'span',new import3.InlineArray2(2,'aria-hidden','true'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'×',(null as any));
    this._text_15 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._text_16 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._text_17 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','modal-body'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._anchor_20 = this.renderer.createTemplateAnchor(this._el_18,(null as any));
    this._vc_20 = new import9.ViewContainer(20,18,this,this._anchor_20);
    this._TemplateRef_20_5 = new import12.TemplateRef_(this,20,this._anchor_20);
    this._NgFor_20_6 = new import11.Wrapper_NgFor(this._vc_20.vcRef,this._TemplateRef_20_5,this.parentView.parentView.injectorGet(import13.IterableDiffers,this.parentView.parentIndex),this.parentView.ref);
    this._text_21 = this.renderer.createText(this._el_18,'\n                ',(null as any));
    this._text_22 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','modal-footer'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n                    ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'button',new import3.InlineArray4(4,'class','btn btn-primary btn-sm','type','submit'),(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_25,'i',new import3.InlineArray2(2,'class','fa fa-save'),(null as any));
    this._text_27 = this.renderer.createText(this._el_25,' Save',(null as any));
    this._text_28 = this.renderer.createText(this._el_23,'\n                ',(null as any));
    this._text_29 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._text_30 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_31 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_4,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_4));
    this._NgForm_4_3.subscribe(this,this.eventHandler(this.handleEvent_4),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._anchor_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._text_31
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (20 === requestNodeIndex))) { return this._TemplateRef_20_5; }
    if (((token === import14.NgFor) && (20 === requestNodeIndex))) { return this._NgFor_20_6.context; }
    if (((token === import33.NgForm) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._NgForm_4_3.context; }
    if (((token === import34.ControlContainer) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._ControlContainer_4_4; }
    if (((token === import23.NgControlStatusGroup) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._NgControlStatusGroup_4_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    this._NgControlStatusGroup_4_5.ngDoCheck(this,this._el_4,throwOnChange);
    const currVal_20_0_0:any = this.parentView.context.cols;
    this._NgFor_20_6.check_ngForOf(currVal_20_0_0,throwOnChange,false);
    this._NgFor_20_6.ngDoCheck(this,this._anchor_20,throwOnChange);
    this._vc_20.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_4_5.checkHost(this,this,this._el_4,throwOnChange);
  }
  destroyInternal():void {
    this._vc_20.destroyNestedViews();
    this._NgForm_4_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 20)) { return new View_ParticipantCrudComponent5(this.viewUtils,this,20,this._anchor_20,this._vc_20); }
    return (null as any);
  }
  handleEvent_4(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_4_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.parentView.context.save()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_ParticipantCrudComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_ParticipantCrudComponent,{});
export class View_ParticipantCrudComponent0 extends import1.AppView<import0.ParticipantCrudComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _DefaultValueAccessor_13_3:import15.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_13_4:any[];
  _NgModel_13_5:import16.Wrapper_NgModel;
  _NgControl_13_6:any;
  _NgControlStatus_13_7:import17.Wrapper_NgControlStatus;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _vc_17:import9.ViewContainer;
  _TemplateRef_17_5:any;
  _NgFor_17_6:import11.Wrapper_NgFor;
  _text_18:any;
  _el_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _anchor_25:any;
  /*private*/ _vc_25:import9.ViewContainer;
  _TemplateRef_25_5:any;
  _NgFor_25_6:import11.Wrapper_NgFor;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _anchor_29:any;
  /*private*/ _vc_29:import9.ViewContainer;
  _TemplateRef_29_5:any;
  _NgIf_29_6:import30.Wrapper_NgIf;
  _text_30:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  _pipe_filter_0:import35.FilterPipe;
  _pipe_filter_0_0:any;
  _pipe_tostring_1:import36.ToStringPipe;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ParticipantCrudComponent0,renderType_ParticipantCrudComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_45 = import10.UNINITIALIZED;
    this._expr_46 = import10.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','card'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','card-header'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'h4',new import3.InlineArray2(2,'class','card-title'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_2,'h6',new import3.InlineArray2(2,'class','card-subtitle mb-2 text-muted'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','card-block'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'input',new import3.InlineArray8(6,'class','form-control mb-2','placeholder','Search','type','text'),(null as any));
    this._DefaultValueAccessor_13_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_13));
    this._NG_VALUE_ACCESSOR_13_4 = [this._DefaultValueAccessor_13_3.context];
    this._NgModel_13_5 = new import16.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_13_4);
    this._NgControl_13_6 = this._NgModel_13_5.context;
    this._NgControlStatus_13_7 = new import17.Wrapper_NgControlStatus(this._NgControl_13_6);
    this._text_14 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','row p-2 bg-faded border-bottom-2'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n            ',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._vc_17 = new import9.ViewContainer(17,15,this,this._anchor_17);
    this._TemplateRef_17_5 = new import12.TemplateRef_(this,17,this._anchor_17);
    this._NgFor_17_6 = new import11.Wrapper_NgFor(this._vc_17.vcRef,this._TemplateRef_17_5,this.parentView.injectorGet(import13.IterableDiffers,this.parentIndex),this.ref);
    this._text_18 = this.renderer.createText(this._el_15,'\n            ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_15,'button',new import3.InlineArray8(6,'class','btn btn-primary btn-sm mr-1','data-target','#editor','data-toggle','modal'),(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_19,'i',new import3.InlineArray2(2,'class','fa fa-plus'),(null as any));
    this._text_21 = this.renderer.createText(this._el_19,' Add...',(null as any));
    this._text_22 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._text_23 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._text_24 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._anchor_25 = this.renderer.createTemplateAnchor(this._el_11,(null as any));
    this._vc_25 = new import9.ViewContainer(25,11,this,this._anchor_25);
    this._TemplateRef_25_5 = new import12.TemplateRef_(this,25,this._anchor_25);
    this._NgFor_25_6 = new import11.Wrapper_NgFor(this._vc_25.vcRef,this._TemplateRef_25_5,this.parentView.injectorGet(import13.IterableDiffers,this.parentIndex),this.ref);
    this._text_26 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._text_27 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._text_28 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_29 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_29 = new import9.ViewContainer(29,0,this,this._anchor_29);
    this._TemplateRef_29_5 = new import12.TemplateRef_(this,29,this._anchor_29);
    this._NgIf_29_6 = new import30.Wrapper_NgIf(this._vc_29.vcRef,this._TemplateRef_29_5);
    this._text_30 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_13,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_13));
    this._NgModel_13_5.subscribe(this,this.eventHandler(this.handleEvent_13),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_19,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_19));
    this._pipe_filter_0 = new import35.FilterPipe();
    this._pipe_filter_0_0 = import3.pureProxy2(this._pipe_filter_0.transform.bind(this._pipe_filter_0));
    this._pipe_tostring_1 = new import36.ToStringPipe();
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._anchor_17,
      this._text_18,
      this._el_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._anchor_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._anchor_29,
      this._text_30
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.DefaultValueAccessor) && (13 === requestNodeIndex))) { return this._DefaultValueAccessor_13_3.context; }
    if (((token === import20.NG_VALUE_ACCESSOR) && (13 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_13_4; }
    if (((token === import21.NgModel) && (13 === requestNodeIndex))) { return this._NgModel_13_5.context; }
    if (((token === import22.NgControl) && (13 === requestNodeIndex))) { return this._NgControl_13_6; }
    if (((token === import23.NgControlStatus) && (13 === requestNodeIndex))) { return this._NgControlStatus_13_7.context; }
    if (((token === import12.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import14.NgFor) && (17 === requestNodeIndex))) { return this._NgFor_17_6.context; }
    if (((token === import12.TemplateRef) && (25 === requestNodeIndex))) { return this._TemplateRef_25_5; }
    if (((token === import14.NgFor) && (25 === requestNodeIndex))) { return this._NgFor_25_6.context; }
    if (((token === import12.TemplateRef) && (29 === requestNodeIndex))) { return this._TemplateRef_29_5; }
    if (((token === import31.NgIf) && (29 === requestNodeIndex))) { return this._NgIf_29_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import10.ValueUnwrapper();
    this._DefaultValueAccessor_13_3.ngDoCheck(this,this._el_13,throwOnChange);
    const currVal_13_1_0:any = this.context.search;
    this._NgModel_13_5.check_model(currVal_13_1_0,throwOnChange,false);
    this._NgModel_13_5.ngDoCheck(this,this._el_13,throwOnChange);
    this._NgControlStatus_13_7.ngDoCheck(this,this._el_13,throwOnChange);
    const currVal_17_0_0:any = this.context.cols;
    this._NgFor_17_6.check_ngForOf(currVal_17_0_0,throwOnChange,false);
    this._NgFor_17_6.ngDoCheck(this,this._anchor_17,throwOnChange);
    valUnwrapper.reset();
    const currVal_25_0_0:any = valUnwrapper.unwrap(import3.castByValue(this._pipe_filter_0_0,this._pipe_filter_0.transform)(this.context.source,this.context.search));
    this._NgFor_25_6.check_ngForOf(currVal_25_0_0,throwOnChange,valUnwrapper.hasWrappedValue);
    this._NgFor_25_6.ngDoCheck(this,this._anchor_25,throwOnChange);
    const currVal_29_0_0:any = (this.context.selected !== (null as any));
    this._NgIf_29_6.check_ngIf(currVal_29_0_0,throwOnChange,false);
    this._NgIf_29_6.ngDoCheck(this,this._anchor_29,throwOnChange);
    this._vc_17.detectChangesInNestedViews(throwOnChange);
    this._vc_25.detectChangesInNestedViews(throwOnChange);
    this._vc_29.detectChangesInNestedViews(throwOnChange);
    const currVal_45:any = import3.inlineInterpolate(1,'',this.context.title,'');
    if (import3.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setText(this._text_5,currVal_45);
      this._expr_45 = currVal_45;
    }
    const currVal_46:any = import3.inlineInterpolate(1,'',this.context.subtitle,'');
    if (import3.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setText(this._text_8,currVal_46);
      this._expr_46 = currVal_46;
    }
    this._NgControlStatus_13_7.checkHost(this,this,this._el_13,throwOnChange);
  }
  destroyInternal():void {
    this._vc_17.destroyNestedViews();
    this._vc_25.destroyNestedViews();
    this._vc_29.destroyNestedViews();
    this._NgModel_13_5.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 17)) { return new View_ParticipantCrudComponent1(this.viewUtils,this,17,this._anchor_17,this._vc_17); }
    if ((nodeIndex == 25)) { return new View_ParticipantCrudComponent2(this.viewUtils,this,25,this._anchor_25,this._vc_25); }
    if ((nodeIndex == 29)) { return new View_ParticipantCrudComponent4(this.viewUtils,this,29,this._anchor_29,this._vc_29); }
    return (null as any);
  }
  handleEvent_13(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_13_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.search = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_19(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.add()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}