/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/components/schedule.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../app/services/schedule.service';
import * as import9 from '@angular/core/src/linker/view_container';
import * as import10 from '@angular/core/src/change_detection/change_detection_util';
import * as import11 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import12 from '@angular/core/src/linker/template_ref';
import * as import13 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import14 from '@angular/common/src/directives/ng_for';
import * as import15 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import16 from '@angular/common/src/directives/ng_if';
import * as import17 from '@angular/core/src/security';
export class Wrapper_ScheduleComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ScheduleComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.ScheduleComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ScheduleComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_ScheduleComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.ScheduleComponent>;
  _ScheduleComponent_0_3:Wrapper_ScheduleComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ScheduleComponent_Host0,renderType_ScheduleComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'sch-schedule',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ScheduleComponent0(this.viewUtils,this,0,this._el_0);
    this._ScheduleComponent_0_3 = new Wrapper_ScheduleComponent(this.injectorGet(import8.ScheduleService,this.parentIndex));
    this.compView_0.create(this._ScheduleComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._ScheduleComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ScheduleComponent) && (0 === requestNodeIndex))) { return this._ScheduleComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ScheduleComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ScheduleComponentNgFactory:import7.ComponentFactory<import0.ScheduleComponent> = new import7.ComponentFactory<import0.ScheduleComponent>('sch-schedule',View_ScheduleComponent_Host0,import0.ScheduleComponent);
const styles_ScheduleComponent:any[] = ([] as any[]);
class View_ScheduleComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ScheduleComponent1,renderType_ScheduleComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_5 = import10.UNINITIALIZED;
    this._expr_6 = import10.UNINITIALIZED;
    this._expr_7 = import10.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_5:any = (this.context.$implicit.status === 'ERROR');
    if (import3.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_2,'table-danger',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = (this.parentView.context.selectedParticipant && (this.context.$implicit.uuid === this.parentView.context.selectedParticipant.uuid));
    if (import3.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_2,'table-info',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_3,currVal_7);
      this._expr_7 = currVal_7;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.display(this.context.$implicit.uuid,'participant')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_ScheduleComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ScheduleComponent2,renderType_ScheduleComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_20 = import10.UNINITIALIZED;
    this._expr_21 = import10.UNINITIALIZED;
    this._expr_22 = import10.UNINITIALIZED;
    this._expr_23 = import10.UNINITIALIZED;
    this._expr_24 = import10.UNINITIALIZED;
    this._expr_25 = import10.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'th',new import3.InlineArray2(2,'scope','row'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'',(null as any));
    this._text_16 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_20:any = import3.inlineInterpolate(1,'',this.context.$implicit[0],'');
    if (import3.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setText(this._text_3,currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = import3.inlineInterpolate(1,'',this.context.$implicit[1],'');
    if (import3.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setText(this._text_6,currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = import3.inlineInterpolate(1,'',this.context.$implicit[2],'');
    if (import3.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setText(this._text_9,currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = import3.inlineInterpolate(1,'',this.context.$implicit[3],'');
    if (import3.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setText(this._text_12,currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = import3.inlineInterpolate(1,'',this.context.$implicit[4],'');
    if (import3.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setText(this._text_15,currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = import3.inlineInterpolate(1,'',this.context.$implicit[5],'');
    if (import3.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setText(this._text_18,currVal_25);
      this._expr_25 = currVal_25;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ScheduleComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ScheduleComponent4,renderType_ScheduleComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_8 = import10.UNINITIALIZED;
    this._expr_9 = import10.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'tr',new import3.InlineArray2(2,'class','table-danger'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'th',new import3.InlineArray2(2,'scope','row'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_8:any = import3.inlineInterpolate(1,'',this.context.$implicit.activity.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_3,currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = import3.inlineInterpolate(1,'',this.context.$implicit.teacher.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setText(this._text_6,currVal_9);
      this._expr_9 = currVal_9;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ScheduleComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _vc_21:import9.ViewContainer;
  _TemplateRef_21_5:any;
  _NgFor_21_6:import11.Wrapper_NgFor;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ScheduleComponent3,renderType_ScheduleComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'h4',new import3.InlineArray2(2,'class','mt-5'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'No solution for:',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'table',new import3.InlineArray2(2,'class','table'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n          ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'thead',new import3.InlineArray2(2,'class','thead-inverse'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n              ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'Activity',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n              ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_9,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'Teacher',(null as any));
    this._text_16 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._text_17 = this.renderer.createText(this._el_7,'\n          ',(null as any));
    this._text_18 = this.renderer.createText(this._el_5,'\n          ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_5,'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._vc_21 = new import9.ViewContainer(21,19,this,this._anchor_21);
    this._TemplateRef_21_5 = new import12.TemplateRef_(this,21,this._anchor_21);
    this._NgFor_21_6 = new import11.Wrapper_NgFor(this._vc_21.vcRef,this._TemplateRef_21_5,this.parentView.parentView.injectorGet(import13.IterableDiffers,this.parentView.parentIndex),this.parentView.ref);
    this._text_22 = this.renderer.createText(this._el_19,'\n          ',(null as any));
    this._text_23 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._text_24 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._text_23,
      this._text_24
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import14.NgFor) && (21 === requestNodeIndex))) { return this._NgFor_21_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_21_0_0:any = this.parentView.context.getProblemsForParticipant(this.parentView.context.selectedParticipant);
    this._NgFor_21_6.check_ngForOf(currVal_21_0_0,throwOnChange,false);
    this._NgFor_21_6.ngDoCheck(this,this._anchor_21,throwOnChange);
    this._vc_21.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_21.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 21)) { return new View_ScheduleComponent4(this.viewUtils,this,21,this._anchor_21,this._vc_21); }
    return (null as any);
  }
}
class View_ScheduleComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ScheduleComponent6,renderType_ScheduleComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_8 = import10.UNINITIALIZED;
    this._expr_9 = import10.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'th',new import3.InlineArray2(2,'scope','row'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_8:any = import3.inlineInterpolate(1,'',this.context.$implicit.activity.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_3,currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = import3.inlineInterpolate(1,'',this.context.$implicit.participant.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setText(this._text_6,currVal_9);
      this._expr_9 = currVal_9;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ScheduleComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _vc_21:import9.ViewContainer;
  _TemplateRef_21_5:any;
  _NgFor_21_6:import11.Wrapper_NgFor;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ScheduleComponent5,renderType_ScheduleComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'h4',new import3.InlineArray2(2,'class','mt-5'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'No solution for:',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'table',new import3.InlineArray2(2,'class','table table-danger'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n          ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'thead',new import3.InlineArray2(2,'class','table-inverse'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n              ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'Activity',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n              ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_9,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'Participant',(null as any));
    this._text_16 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._text_17 = this.renderer.createText(this._el_7,'\n          ',(null as any));
    this._text_18 = this.renderer.createText(this._el_5,'\n          ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_5,'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._vc_21 = new import9.ViewContainer(21,19,this,this._anchor_21);
    this._TemplateRef_21_5 = new import12.TemplateRef_(this,21,this._anchor_21);
    this._NgFor_21_6 = new import11.Wrapper_NgFor(this._vc_21.vcRef,this._TemplateRef_21_5,this.parentView.parentView.injectorGet(import13.IterableDiffers,this.parentView.parentIndex),this.parentView.ref);
    this._text_22 = this.renderer.createText(this._el_19,'\n          ',(null as any));
    this._text_23 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._text_24 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._text_23,
      this._text_24
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import14.NgFor) && (21 === requestNodeIndex))) { return this._NgFor_21_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_21_0_0:any = this.parentView.context.getProblemsForTeacher(this.parentView.context.selectedTeacher);
    this._NgFor_21_6.check_ngForOf(currVal_21_0_0,throwOnChange,false);
    this._NgFor_21_6.ngDoCheck(this,this._anchor_21,throwOnChange);
    this._vc_21.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_21.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 21)) { return new View_ScheduleComponent6(this.viewUtils,this,21,this._anchor_21,this._vc_21); }
    return (null as any);
  }
}
class View_ScheduleComponent7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ScheduleComponent7,renderType_ScheduleComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_5 = import10.UNINITIALIZED;
    this._expr_6 = import10.UNINITIALIZED;
    this._expr_7 = import10.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_5:any = (this.context.$implicit.status === 'ERROR');
    if (import3.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_2,'table-danger',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = (this.parentView.context.selectedTeacher && (this.context.$implicit.uuid === this.parentView.context.selectedTeacher.uuid));
    if (import3.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_2,'table-info',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = import3.inlineInterpolate(1,'',this.context.$implicit.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_3,currVal_7);
      this._expr_7 = currVal_7;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.display(this.context.$implicit.uuid,'teacher')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_ScheduleComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_ScheduleComponent,{});
export class View_ScheduleComponent0 extends import1.AppView<import0.ScheduleComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _anchor_38:any;
  /*private*/ _vc_38:import9.ViewContainer;
  _TemplateRef_38_5:any;
  _NgFor_38_6:import11.Wrapper_NgFor;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _el_53:any;
  _el_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _text_68:any;
  _el_69:any;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _anchor_76:any;
  /*private*/ _vc_76:import9.ViewContainer;
  _TemplateRef_76_5:any;
  _NgFor_76_6:import11.Wrapper_NgFor;
  _text_77:any;
  _text_78:any;
  _text_79:any;
  _text_80:any;
  _anchor_81:any;
  /*private*/ _vc_81:import9.ViewContainer;
  _TemplateRef_81_5:any;
  _NgIf_81_6:import15.Wrapper_NgIf;
  _text_82:any;
  _anchor_83:any;
  /*private*/ _vc_83:import9.ViewContainer;
  _TemplateRef_83_5:any;
  _NgIf_83_6:import15.Wrapper_NgIf;
  _text_84:any;
  _text_85:any;
  _el_86:any;
  _text_87:any;
  _el_88:any;
  _text_89:any;
  _el_90:any;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _el_94:any;
  _text_95:any;
  _text_96:any;
  _text_97:any;
  _text_98:any;
  _el_99:any;
  _text_100:any;
  _anchor_101:any;
  /*private*/ _vc_101:import9.ViewContainer;
  _TemplateRef_101_5:any;
  _NgFor_101_6:import11.Wrapper_NgFor;
  _text_102:any;
  _text_103:any;
  _text_104:any;
  _text_105:any;
  /*private*/ _expr_121:any;
  /*private*/ _expr_122:any;
  /*private*/ _expr_123:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ScheduleComponent0,renderType_ScheduleComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_121 = import10.UNINITIALIZED;
    this._expr_122 = import10.UNINITIALIZED;
    this._expr_123 = import10.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row mb-2 ml-2'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'button',new import3.InlineArray4(4,'class','btn btn-outline-info','type','button'),(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_4,'i',new import3.InlineArray2(2,'class','fa fa-calendar'),(null as any));
    this._text_6 = this.renderer.createText(this._el_4,' Generate schedule',(null as any));
    this._text_7 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_2,'button',new import3.InlineArray4(4,'class','btn btn-outline-info ml-2','type','button'),(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_8,'i',new import3.InlineArray2(2,'class','fa fa-calendar-o'),(null as any));
    this._text_10 = this.renderer.createText(this._el_8,' Clear schedule',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_2,'span',new import3.InlineArray2(2,'class','text-info ml-4 mt-2'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','progress mt-2 mb-2'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'div',new import3.InlineArray8(8,'aria-valuemax','10','aria-valuemin','0','class','progress-bar progress-bar-striped progress-bar-animated','role','progressbar'),(null as any));
    this._text_19 = this.renderer.createText(this._el_16,'\n  ',(null as any));
    this._text_20 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n    ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_21,'div',new import3.InlineArray2(2,'class','col-sm-2'),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n      ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'table',new import3.InlineArray2(2,'class','table'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n        ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_25,'thead',new import3.InlineArray2(2,'class','table-inverse'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n          ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_27,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'\n            ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_29,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'Student group',(null as any));
    this._text_33 = this.renderer.createText(this._el_29,'\n          ',(null as any));
    this._text_34 = this.renderer.createText(this._el_27,'\n        ',(null as any));
    this._text_35 = this.renderer.createText(this._el_25,'\n        ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_25,'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'\n          ',(null as any));
    this._anchor_38 = this.renderer.createTemplateAnchor(this._el_36,(null as any));
    this._vc_38 = new import9.ViewContainer(38,36,this,this._anchor_38);
    this._TemplateRef_38_5 = new import12.TemplateRef_(this,38,this._anchor_38);
    this._NgFor_38_6 = new import11.Wrapper_NgFor(this._vc_38.vcRef,this._TemplateRef_38_5,this.parentView.injectorGet(import13.IterableDiffers,this.parentIndex),this.ref);
    this._text_39 = this.renderer.createText(this._el_36,'\n        ',(null as any));
    this._text_40 = this.renderer.createText(this._el_25,'\n      ',(null as any));
    this._text_41 = this.renderer.createText(this._el_23,'\n    ',(null as any));
    this._text_42 = this.renderer.createText(this._el_21,'\n    ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_21,'div',new import3.InlineArray2(2,'class','col-sm-8'),(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'\n      ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_43,'div',new import3.InlineArray2(2,'class','table-wrapper-scrollable'),(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'\n        ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_45,'table',new import3.InlineArray2(2,'class','table'),(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'\n          ',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_47,'thead',new import3.InlineArray2(2,'class','table-inverse'),(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'\n            ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_49,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'\n              ',(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_51,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_53,'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'Time',(null as any));
    this._text_56 = this.renderer.createText(this._el_51,'\n              ',(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,this._el_51,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'Monday',(null as any));
    this._text_59 = this.renderer.createText(this._el_51,'\n              ',(null as any));
    this._el_60 = import3.createRenderElement(this.renderer,this._el_51,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_61 = this.renderer.createText(this._el_60,'Tuesday',(null as any));
    this._text_62 = this.renderer.createText(this._el_51,'\n              ',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,this._el_51,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'Wednesday',(null as any));
    this._text_65 = this.renderer.createText(this._el_51,'\n              ',(null as any));
    this._el_66 = import3.createRenderElement(this.renderer,this._el_51,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_67 = this.renderer.createText(this._el_66,'Thursday',(null as any));
    this._text_68 = this.renderer.createText(this._el_51,'\n              ',(null as any));
    this._el_69 = import3.createRenderElement(this.renderer,this._el_51,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_70 = this.renderer.createText(this._el_69,'Friday',(null as any));
    this._text_71 = this.renderer.createText(this._el_51,'\n            ',(null as any));
    this._text_72 = this.renderer.createText(this._el_49,'\n          ',(null as any));
    this._text_73 = this.renderer.createText(this._el_47,'\n          ',(null as any));
    this._el_74 = import3.createRenderElement(this.renderer,this._el_47,'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_75 = this.renderer.createText(this._el_74,'\n            ',(null as any));
    this._anchor_76 = this.renderer.createTemplateAnchor(this._el_74,(null as any));
    this._vc_76 = new import9.ViewContainer(76,74,this,this._anchor_76);
    this._TemplateRef_76_5 = new import12.TemplateRef_(this,76,this._anchor_76);
    this._NgFor_76_6 = new import11.Wrapper_NgFor(this._vc_76.vcRef,this._TemplateRef_76_5,this.parentView.injectorGet(import13.IterableDiffers,this.parentIndex),this.ref);
    this._text_77 = this.renderer.createText(this._el_74,'\n          ',(null as any));
    this._text_78 = this.renderer.createText(this._el_47,'\n        ',(null as any));
    this._text_79 = this.renderer.createText(this._el_45,'\n      ',(null as any));
    this._text_80 = this.renderer.createText(this._el_43,'\n      ',(null as any));
    this._anchor_81 = this.renderer.createTemplateAnchor(this._el_43,(null as any));
    this._vc_81 = new import9.ViewContainer(81,43,this,this._anchor_81);
    this._TemplateRef_81_5 = new import12.TemplateRef_(this,81,this._anchor_81);
    this._NgIf_81_6 = new import15.Wrapper_NgIf(this._vc_81.vcRef,this._TemplateRef_81_5);
    this._text_82 = this.renderer.createText(this._el_43,'\n      ',(null as any));
    this._anchor_83 = this.renderer.createTemplateAnchor(this._el_43,(null as any));
    this._vc_83 = new import9.ViewContainer(83,43,this,this._anchor_83);
    this._TemplateRef_83_5 = new import12.TemplateRef_(this,83,this._anchor_83);
    this._NgIf_83_6 = new import15.Wrapper_NgIf(this._vc_83.vcRef,this._TemplateRef_83_5);
    this._text_84 = this.renderer.createText(this._el_43,'\n    ',(null as any));
    this._text_85 = this.renderer.createText(this._el_21,'\n    ',(null as any));
    this._el_86 = import3.createRenderElement(this.renderer,this._el_21,'div',new import3.InlineArray2(2,'class','col-sm-2'),(null as any));
    this._text_87 = this.renderer.createText(this._el_86,'\n      ',(null as any));
    this._el_88 = import3.createRenderElement(this.renderer,this._el_86,'table',new import3.InlineArray2(2,'class','table'),(null as any));
    this._text_89 = this.renderer.createText(this._el_88,'\n        ',(null as any));
    this._el_90 = import3.createRenderElement(this.renderer,this._el_88,'thead',new import3.InlineArray2(2,'class','table-inverse'),(null as any));
    this._text_91 = this.renderer.createText(this._el_90,'\n          ',(null as any));
    this._el_92 = import3.createRenderElement(this.renderer,this._el_90,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_93 = this.renderer.createText(this._el_92,'\n            ',(null as any));
    this._el_94 = import3.createRenderElement(this.renderer,this._el_92,'th',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_95 = this.renderer.createText(this._el_94,'Teachers',(null as any));
    this._text_96 = this.renderer.createText(this._el_92,'\n          ',(null as any));
    this._text_97 = this.renderer.createText(this._el_90,'\n        ',(null as any));
    this._text_98 = this.renderer.createText(this._el_88,'\n        ',(null as any));
    this._el_99 = import3.createRenderElement(this.renderer,this._el_88,'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_100 = this.renderer.createText(this._el_99,'\n          ',(null as any));
    this._anchor_101 = this.renderer.createTemplateAnchor(this._el_99,(null as any));
    this._vc_101 = new import9.ViewContainer(101,99,this,this._anchor_101);
    this._TemplateRef_101_5 = new import12.TemplateRef_(this,101,this._anchor_101);
    this._NgFor_101_6 = new import11.Wrapper_NgFor(this._vc_101.vcRef,this._TemplateRef_101_5,this.parentView.injectorGet(import13.IterableDiffers,this.parentIndex),this.ref);
    this._text_102 = this.renderer.createText(this._el_99,'\n        ',(null as any));
    this._text_103 = this.renderer.createText(this._el_88,'\n      ',(null as any));
    this._text_104 = this.renderer.createText(this._el_86,'\n    ',(null as any));
    this._text_105 = this.renderer.createText(this._el_21,'\n  ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_4,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_4));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_8,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_8));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._anchor_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._text_71,
      this._text_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._anchor_76,
      this._text_77,
      this._text_78,
      this._text_79,
      this._text_80,
      this._anchor_81,
      this._text_82,
      this._anchor_83,
      this._text_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._el_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._el_94,
      this._text_95,
      this._text_96,
      this._text_97,
      this._text_98,
      this._el_99,
      this._text_100,
      this._anchor_101,
      this._text_102,
      this._text_103,
      this._text_104,
      this._text_105
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (38 === requestNodeIndex))) { return this._TemplateRef_38_5; }
    if (((token === import14.NgFor) && (38 === requestNodeIndex))) { return this._NgFor_38_6.context; }
    if (((token === import12.TemplateRef) && (76 === requestNodeIndex))) { return this._TemplateRef_76_5; }
    if (((token === import14.NgFor) && (76 === requestNodeIndex))) { return this._NgFor_76_6.context; }
    if (((token === import12.TemplateRef) && (81 === requestNodeIndex))) { return this._TemplateRef_81_5; }
    if (((token === import16.NgIf) && (81 === requestNodeIndex))) { return this._NgIf_81_6.context; }
    if (((token === import12.TemplateRef) && (83 === requestNodeIndex))) { return this._TemplateRef_83_5; }
    if (((token === import16.NgIf) && (83 === requestNodeIndex))) { return this._NgIf_83_6.context; }
    if (((token === import12.TemplateRef) && (101 === requestNodeIndex))) { return this._TemplateRef_101_5; }
    if (((token === import14.NgFor) && (101 === requestNodeIndex))) { return this._NgFor_101_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_38_0_0:any = this.context.source.participants;
    this._NgFor_38_6.check_ngForOf(currVal_38_0_0,throwOnChange,false);
    this._NgFor_38_6.ngDoCheck(this,this._anchor_38,throwOnChange);
    const currVal_76_0_0:any = this.context.displaySchedule;
    this._NgFor_76_6.check_ngForOf(currVal_76_0_0,throwOnChange,false);
    this._NgFor_76_6.ngDoCheck(this,this._anchor_76,throwOnChange);
    const currVal_81_0_0:any = (this.context.selectedParticipant && (this.context.selectedParticipant.status === 'ERROR'));
    this._NgIf_81_6.check_ngIf(currVal_81_0_0,throwOnChange,false);
    this._NgIf_81_6.ngDoCheck(this,this._anchor_81,throwOnChange);
    const currVal_83_0_0:any = (this.context.selectedTeacher && (this.context.selectedTeacher.status === 'ERROR'));
    this._NgIf_83_6.check_ngIf(currVal_83_0_0,throwOnChange,false);
    this._NgIf_83_6.ngDoCheck(this,this._anchor_83,throwOnChange);
    const currVal_101_0_0:any = this.context.source.teachers;
    this._NgFor_101_6.check_ngForOf(currVal_101_0_0,throwOnChange,false);
    this._NgFor_101_6.ngDoCheck(this,this._anchor_101,throwOnChange);
    this._vc_38.detectChangesInNestedViews(throwOnChange);
    this._vc_76.detectChangesInNestedViews(throwOnChange);
    this._vc_81.detectChangesInNestedViews(throwOnChange);
    this._vc_83.detectChangesInNestedViews(throwOnChange);
    this._vc_101.detectChangesInNestedViews(throwOnChange);
    const currVal_121:any = import3.inlineInterpolate(1,'There are ',this.context.source.noSolutionFor.length,' impossible allocations.');
    if (import3.checkBinding(throwOnChange,this._expr_121,currVal_121)) {
      this.renderer.setText(this._text_13,currVal_121);
      this._expr_121 = currVal_121;
    }
    const currVal_122:any = (((this.context.progress.current / 10) * 100) + '%');
    if (import3.checkBinding(throwOnChange,this._expr_122,currVal_122)) {
      this.renderer.setElementStyle(this._el_18,'width',((this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_122) == null)? (null as any): this.viewUtils.sanitizer.sanitize(import17.SecurityContext.STYLE,currVal_122).toString()));
      this._expr_122 = currVal_122;
    }
    const currVal_123:any = this.context.progress.current;
    if (import3.checkBinding(throwOnChange,this._expr_123,currVal_123)) {
      this.renderer.setElementAttribute(this._el_18,'aria-valuenow',((currVal_123 == null)? (null as any): currVal_123.toString()));
      this._expr_123 = currVal_123;
    }
  }
  destroyInternal():void {
    this._vc_38.destroyNestedViews();
    this._vc_76.destroyNestedViews();
    this._vc_81.destroyNestedViews();
    this._vc_83.destroyNestedViews();
    this._vc_101.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 38)) { return new View_ScheduleComponent1(this.viewUtils,this,38,this._anchor_38,this._vc_38); }
    if ((nodeIndex == 76)) { return new View_ScheduleComponent2(this.viewUtils,this,76,this._anchor_76,this._vc_76); }
    if ((nodeIndex == 81)) { return new View_ScheduleComponent3(this.viewUtils,this,81,this._anchor_81,this._vc_81); }
    if ((nodeIndex == 83)) { return new View_ScheduleComponent5(this.viewUtils,this,83,this._anchor_83,this._vc_83); }
    if ((nodeIndex == 101)) { return new View_ScheduleComponent7(this.viewUtils,this,101,this._anchor_101,this._vc_101); }
    return (null as any);
  }
  handleEvent_4(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.generateSchedule()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_8(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.clearSchedule()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}